- name: Install and configure Grafana on Azure VM
  hosts: grafana
  gather_facts: yes
  become: yes

  tasks:
  - name: Update package cache and upgrade packages
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install required packages
    apt:
      name: 
        - apt-transport-https
        - software-properties-common
      state: present

  - name: Add Grafana repository key
    apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present

  - name: Add Grafana repository
    apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present

  - name: Install Grafana
    apt:
      name: grafana
      state: present

  - name: Start and enable Grafana service
    systemd:
      name: grafana-server
      enabled: yes
      state: started

  - name: Configure Grafana
    lineinfile:
      path: /etc/grafana/grafana.ini
      regexp: '{{ item.regexp }}'
      line: '{{ item.line }}'
    with_items:
      - { regexp: '^http_port = .*', line: 'http_port = 3000' }
      - { regexp: '^;domain = .*', line: 'domain = {{ ansible_fqdn }}' }

  - name: Restart Grafana service
    systemd:
      name: grafana-server
      state: restarted



  - name: change admin password for grafana gui
    shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
    register: __command_admin
     changed_when: __command_admin.rc !=0
